### ISSUE TITLE
The Control is not made available

### ISSUE THREAD

**Issue by Octavianbr** [brasov2de/ColorfulOptionsetGrid#17]
I have installed the ColorfulOptionsetGridSol_managed.zip solution on my DEV org (online).
Everything went ok but the control is not in the available ones for an option set field.
I get only only 4 but yours was not between them. 
Anything else I should to make it work?

Regards and thank you!

**Comment by brasov2de** [comment]
Hi  @Octavianbr , 

What you are looking for is the ColorfulOptionset PCF (https://github.com/ORBISAG/ORBIS.PCF.ColorfulOptionset). There you will find the PCF who can be used as an Optionset Control.
This repository is the ColorfulOptionsetGrid, which is a dataset PCF, who can be attached on views or entitiy grids.

Kind regards,
Diana
