### ISSUE TITLE
Column Filter Issue

### ISSUE THREAD

**Issue by marisolcastro73** [brasov2de/ColorfulOptionsetGrid#20]
I installed the managed version for this plugin on my Dynamics 365 instance.  I applied the custom control to my view for my Priority option set field.  Once I did this the ability to filter columns in my system view was removed.  This is needed in order to filter by various items in this system view for my end users that I support.  Is there any way to add filtering back to the columns and keep this custom control?

**Comment by brasov2de** [comment]
Hi @marisolcastro73 , 
Unfortunately we cannot take features from the standard grid. We need to implement every feature by our own.
I'll have a look how much effort is needed, and when I get the time for it. But I cannot promise a release date for it.

**Comment by brasov2de** [comment]
In future we'll be able to use a grid-renderer for the Power Apps Grid (preview). There the standard column filter can be used, while we can customize controls. When that's GA, I guess we won't need the colorful optionset grid anymore.
Have a look to my blog: https://dianabirkelbach.wordpress.com/2022/07/27/power-apps-grid-control-first-glimpse-to-the-cell-renderer-and-editors/
