### ISSUE TITLE
ColorfulOptionSetGrid is not shown in a grid displayed dashboard.

### ISSUE THREAD

**Issue by saadnadir** [brasov2de/ColorfulOptionsetGrid#23]
I have applied the configuration for a specific grid. I was able to see the rendering of the control when i was displaying it from the sitemap.

When i added the same grid to a dashboard, the control did not shown.

**Comment by rc2378** [comment]
I'm seeing the same behavior for a grid embedded in a form.

**Comment by rc2378** [comment]
> I have applied the configuration for a specific grid. I was able to see the rendering of the control when i was displaying it from the sitemap.
> 
> When i added the same grid to a dashboard, the control did not shown.

Make sure you go to the control in the dashboard/form and change the control to ColorfulOptionSetGrid

**Comment by brasov2de** [comment]
I could reproduce the issue on forms, after resizing top fullScreen/and back.
Made a new release. Hope that fixes your issue.
@saadnadir
