### ISSUE TITLE
I cannot apply the optionset to more than 3 columns

### ISSUE THREAD

**Issue by pjesst** [brasov2de/ColorfulOptionsetGrid#26]
Is there a way to change the property of dataset to accommodate more columns... right now it allows only 3

**Comment by brasov2de** [comment]
You need the 3 columns only if you want to customize them differently.
If you don't specify any column at all, all the columns in the view will apply the default icon / display mode and will use the colors defined in each optionset column (choice).
Does this solve you issue?

**Comment by pjesst** [comment]
Hello Diana,

Thank you for the reply, it works.  I mis-understood the customization.

Regards,
Priya

From: Diana Birkelbach ***@***.***>
Sent: August 12, 2022 1:16 PM
To: brasov2de/ColorfulOptionsetGrid ***@***.***>
Cc: Telkar, Priya J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [brasov2de/ColorfulOptionsetGrid] I cannot apply the optionset to more than 3 columns (Issue #26)


You need the 3 columns only if you want to customize them differently.
If you don't specify any column at all, all the columns in the view will apply the default icon / display mode and will use the colors defined in each optionset column (choice).
Does this solve you issue?
