### ISSUE TITLE
Filter does not work on the entity where the solution is used

### ISSUE THREAD

**Issue by pjesst** [brasov2de/ColorfulOptionsetGrid#27]

**Comment by brasov2de** [comment]
Do you mean the column filter? Thid Rgid doesn't have this feature implemented.

**Comment by pjesst** [comment]
Yes, the column filter

From: Diana Birkelbach ***@***.***>
Sent: August 30, 2022 1:22 PM
To: brasov2de/ColorfulOptionsetGrid ***@***.***>
Cc: Telkar, Priya J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [brasov2de/ColorfulOptionsetGrid] Filter does not work on the entity where the solution is used (Issue #27)


Do you mean the column filter? Thid Rgid doesn't have this feature implemented.

**Comment by brasov2de** [comment]
Implementing that kind of filter would take a lot of time.
But the good news is: Microsoft allows up to extend the Power Apps Grid. That control has all the out-of-the-box features and allows us to change the way the cells are looking like. So there the column filter works too,
Have a look to my blog: https://dianabirkelbach.wordpress.com/2022/07/27/power-apps-grid-control-first-glimpse-to-the-cell-renderer-and-editors/  or to my youtube video: https://www.youtube.com/watch?v=PP7oe1LgPvw&t=21s&ab_channel=DianaBirkelbachakaDianamicsPCFLady

It's in preview for now, but we'll get a platform-way soon.

**Comment by pjesst** [comment]
Hello Diana,

Thank you for sharing the below info, this is helpful.

Regards,
Priya

From: Diana Birkelbach ***@***.***>
Sent: August 30, 2022 1:29 PM
To: brasov2de/ColorfulOptionsetGrid ***@***.***>
Cc: Telkar, Priya J ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [brasov2de/ColorfulOptionsetGrid] Filter does not work on the entity where the solution is used (Issue #27)


Implementing that kind of filter would take a lot of time.
But the good news is: Microsoft allows up to extend the Power Apps Grid. That control has all the out-of-the-box features and allows us to change the way the cells are looking like. So there the column filter works too,
Have a look to my blog: https://dianabirkelbach.wordpress.com/2022/07/27/power-apps-grid-control-first-glimpse-to-the-cell-renderer-and-editors/ or to my youtube video: https://www.youtube.com/watch?v=PP7oe1LgPvw&t=21s&ab_channel=DianaBirkelbachakaDianamicsPCFLady

It's in preview for now, but we'll get a platform-way soon.
