### ISSUE TITLE
getting invalid solution file error

### ISSUE THREAD

**Issue by ApoorvaGhavri21** [brasov2de/ColorfulOptionsetGrid#28]
Getting below error while importing the solution
The solution file is invalid. The compressed file must contain the following files at its root: solution.xml, customizations.xml, and [Content_Types].xml. Customization files exported from previous versions of Microsoft Dynamics 365 are not supported.

**Comment by brasov2de** [comment]
Hi @ApoorvaGhavri21 , 
You find the solutions by navigating to "releases": https://github.com/brasov2de/ColorfulOptionsetGrid/releases
and download one of the solutions, depending if you want a managed or unmanaged solution (marked red on the screenshot): 
![image](https://user-images.githubusercontent.com/29977935/192566273-d172e281-dee4-451a-ba58-d22ad112c4a1.png)
Just import that zip.
If you look inside the zips, you find the xml files listed in your message.
