### ISSUE TITLE
Colorfuloptionsetgrid not showing up 

### ISSUE THREAD

**Issue by ApoorvaGhavri21** [brasov2de/ColorfulOptionsetGrid#29]
I added the custom control to view from classic editor . But the customizations are not appearing.

**Comment by brasov2de** [comment]
So you added a subgrid to your form, and went to Control, and there you cannot find the ColorfulOptionsetGrid in the list?
Have you installed the unmanaged or the managed version of the PCF?
If unmanaged, have you published after the import?

**Comment by ApoorvaGhavri21** [comment]
Hi I have added in the view.
And I am using unmanaged solution

**Comment by brasov2de** [comment]
Using the new maker portal, you are not reminded to publish. But the publish is needed (publishAll)
Do you mean that the PCF is not shown in the list?
Or maybe you added the PCF already, but you don't see it while running tha App?

**Comment by ApoorvaGhavri21** [comment]
Yes the pcf is not shown  in list

**Comment by ApoorvaGhavri21** [comment]
You mean I have to publish all customisation?

**Comment by brasov2de** [comment]
Yes, please.
If it still doesn't work: 
- have you used JSON configuration for icons?
- using chrome developer tools, you could eventually see errors in the console. Can you find something?

**Comment by ApoorvaGhavri21** [comment]
I am not using json configuration.
But i am applying It on view
And as you told I have published all customisation

**Comment by StuartMHarrod** [comment]
Hi Diana, I am finding when using it on a Model Driven Power App, I can apply apply it to a view, but it then works intermittently, so often doesn't show.

**Comment by brasov2de** [comment]
Hi @StuartMHarrod , 
Does it work if you apply it for the complete table (not only a view)?
Are you able to switch the represenation "use the "Show As ColorfulOptionsetGrid"? Does it work then?

**Comment by StuartMHarrod** [comment]
Hi @brasov2de ,

Yes, that's worked thank you. For some reason I thought I had to apply it directly to the view control.
