### ISSUE TITLE
When embedding the grid in a tab on a form, the options to add/edit/delete records disappear

### ISSUE THREAD

**Issue by rc2378** [brasov2de/ColorfulOptionsetGrid#30]
The standard grid shows all of the subgrid menu options while the Colorful Option Set does not.  You also cannot switch back to the standard grid without refreshing and reloading the form.

Standard grid:
![image](https://user-images.githubusercontent.com/81383857/193266692-d9de0f51-a1df-48be-9a12-8205dcc5d117.png)

Colorful Option Set Grid:
![image](https://user-images.githubusercontent.com/81383857/193266994-113bf4c9-9270-4a5e-8f80-a7b02342a0aa.png)

**Comment by brasov2de** [comment]
Hi @rc2378 , 

fixed that on the latest release (9.2).

Kind regards,
Diana
