### ISSUE TITLE
command bar no longer displayed after PCF activation on grid

### ISSUE THREAD

**Issue by AyouHA** [brasov2de/ColorfulOptionsetGrid#31]
Hi ,

When i use the ColorfulOptionsetGrid the command bar of my subgrid is no longer display
You will find attached the screenshots screen

![test](https://user-images.githubusercontent.com/117101627/199047714-888d68be-ef44-4cb4-ac21-654f3e542a15.png)
![test2](https://user-images.githubusercontent.com/117101627/199047716-c9fe4708-6af0-4fd6-b9f9-08f4b7df5b4e.png)

**Comment by brasov2de** [comment]
Hi @AyouHA , 

I've managed to make a new release (9.2) to fix this issue. 
If you have problems, please reopen the issue.

Kind regards,
Diana
