### ISSUE TITLE
Which File to Import to Solution

### ISSUE THREAD

**Issue by MANEnterprise-Joseph** [brasov2de/ColorfulOptionsetGrid#37]
Hello Which directory shall I download and import to my D365 solution? Sorry I'm still new to PCF.

**Comment by brasov2de** [comment]
Under https://github.com/brasov2de/ColorfulOptionsetGrid/releases, you can take the latest Release (currently 9.2) and download the ColorfulOptionsetGridSol_managed.zip. This is a solution you can import in your environment.

**Comment by MANEnterprise-Joseph** [comment]
Thank you so much. I imported it successfully. Should I do an additional step in order to be able to use it?

**Comment by brasov2de** [comment]
After import, you just need to register the CoplorfulOptionSsetGrid PCF on your Subgrid or view/table and set the options/settings as you wish. The description is provided on this repository. A few more details can be found in this blog: https://dianabirkelbach.wordpress.com/2022/04/24/colorful-optionset-pcf-virtual-and-improved/

**Comment by MANEnterprise-Joseph** [comment]
Hello, sorry to be bothering you again. I went to your blog but I couldn't find some kind of documentation. I'm trying to go to Prospects (Leads) to add the control to a choice field called Country (in order to color the country selected), but when I click add control the CoplorfulOptionSsetGrid is not appearing. What step am I missing? How do I register the CoplorfulOptionSsetGrid  PCF?

**Comment by brasov2de** [comment]
Hi @MANEnterprise-Joseph , 
Then I guess you need the ColorfulOptionset PCF (not the Colorful Optionset Grid as we talked before). You can find it here: https://github.com/ORBISAG/ORBIS.PCF.ColorfulOptionset/releases
This one can be used on Optionset (Choices) fields. The docs are here https://github.com/ORBISAG/ORBIS.PCF.ColorfulOptionset or this blog https://dianabirkelbach.wordpress.com/2022/04/24/colorful-optionset-pcf-virtual-and-improved/
